# Generated by Django 5.0 on 2026-03-09 12:02
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currency_app", "0001_initial"),
    ]
    operations = [
        migrations.AlterModelOptions(
            name="currencyrate",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="currencyrate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="currencyrate",
            name="rate_buy",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="currencyrate",
            name="rate_cross",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="currencyrate",
            name="rate_sell",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddIndex(
            model_name="currencyrate",
            index=models.Index(
                fields=["currency", "-created_at"], name="curr_rate_curr_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="currencyrate",
            index=models.Index(fields=["-created_at"], name="curr_rate_date_idx"),
        ),
    ]
